# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'htmleditor.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(659, 398)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.South)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.webView = QtWebEngineWidgets.QWebEngineView(self.tab)
        self.webView.setUrl(QtCore.QUrl("about:blank"))
        self.webView.setObjectName("webView")
        self.verticalLayout_2.addWidget(self.webView)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.tab_2)
        self.plainTextEdit.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout_3.addWidget(self.plainTextEdit)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 659, 26))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menu_Edit = QtWidgets.QMenu(self.menubar)
        self.menu_Edit.setObjectName("menu_Edit")
        self.menuF_ormat = QtWidgets.QMenu(self.menubar)
        self.menuF_ormat.setObjectName("menuF_ormat")
        self.menuSt_yle = QtWidgets.QMenu(self.menuF_ormat)
        self.menuSt_yle.setObjectName("menuSt_yle")
        self.menu_Align = QtWidgets.QMenu(self.menuF_ormat)
        self.menu_Align.setObjectName("menu_Align")
        MainWindow.setMenuBar(self.menubar)
        self.standardToolBar = QtWidgets.QToolBar(MainWindow)
        self.standardToolBar.setObjectName("standardToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.standardToolBar)
        self.formatToolBar = QtWidgets.QToolBar(MainWindow)
        self.formatToolBar.setObjectName("formatToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.formatToolBar)
        MainWindow.insertToolBarBreak(self.formatToolBar)
        self.actionFileNew = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/document-new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFileNew.setIcon(icon)
        self.actionFileNew.setObjectName("actionFileNew")
        self.actionFileOpen = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/document-open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFileOpen.setIcon(icon1)
        self.actionFileOpen.setObjectName("actionFileOpen")
        self.actionFileSave = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/document-save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFileSave.setIcon(icon2)
        self.actionFileSave.setObjectName("actionFileSave")
        self.actionFileSaveAs = QtWidgets.QAction(MainWindow)
        self.actionFileSaveAs.setObjectName("actionFileSaveAs")
        self.actionEditUndo = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/edit-undo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEditUndo.setIcon(icon3)
        self.actionEditUndo.setObjectName("actionEditUndo")
        self.actionEditRedo = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/edit-redo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEditRedo.setIcon(icon4)
        self.actionEditRedo.setObjectName("actionEditRedo")
        self.actionEditCut = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/edit-cut.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEditCut.setIcon(icon5)
        self.actionEditCut.setObjectName("actionEditCut")
        self.actionEditCopy = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/images/edit-copy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEditCopy.setIcon(icon6)
        self.actionEditCopy.setObjectName("actionEditCopy")
        self.actionEditPaste = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/images/edit-paste.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEditPaste.setIcon(icon7)
        self.actionEditPaste.setObjectName("actionEditPaste")
        self.actionEditSelectAll = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/images/edit-select-all.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEditSelectAll.setIcon(icon8)
        self.actionEditSelectAll.setObjectName("actionEditSelectAll")
        self.actionFormatBold = QtWidgets.QAction(MainWindow)
        self.actionFormatBold.setCheckable(True)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/images/format-text-bold.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFormatBold.setIcon(icon9)
        self.actionFormatBold.setObjectName("actionFormatBold")
        self.actionFormatItalic = QtWidgets.QAction(MainWindow)
        self.actionFormatItalic.setCheckable(True)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/images/format-text-italic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFormatItalic.setIcon(icon10)
        self.actionFormatItalic.setObjectName("actionFormatItalic")
        self.actionFormatUnderline = QtWidgets.QAction(MainWindow)
        self.actionFormatUnderline.setCheckable(True)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/images/format-text-underline.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFormatUnderline.setIcon(icon11)
        self.actionFormatUnderline.setObjectName("actionFormatUnderline")
        self.actionFormatStrikethrough = QtWidgets.QAction(MainWindow)
        self.actionFormatStrikethrough.setCheckable(True)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/images/format-text-strikethrough.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFormatStrikethrough.setIcon(icon12)
        self.actionFormatStrikethrough.setObjectName("actionFormatStrikethrough")
        self.actionFormatAlignLeft = QtWidgets.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/images/format-justify-left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFormatAlignLeft.setIcon(icon13)
        self.actionFormatAlignLeft.setObjectName("actionFormatAlignLeft")
        self.actionFormatAlignCenter = QtWidgets.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/images/format-justify-center.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFormatAlignCenter.setIcon(icon14)
        self.actionFormatAlignCenter.setObjectName("actionFormatAlignCenter")
        self.actionFormatAlignRight = QtWidgets.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/images/format-justify-right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFormatAlignRight.setIcon(icon15)
        self.actionFormatAlignRight.setObjectName("actionFormatAlignRight")
        self.actionFormatAlignJustify = QtWidgets.QAction(MainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/images/format-justify-fill.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFormatAlignJustify.setIcon(icon16)
        self.actionFormatAlignJustify.setObjectName("actionFormatAlignJustify")
        self.actionFormatIncreaseIndent = QtWidgets.QAction(MainWindow)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/images/format-indent-more.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFormatIncreaseIndent.setIcon(icon17)
        self.actionFormatIncreaseIndent.setObjectName("actionFormatIncreaseIndent")
        self.actionFormatDecreaseIndent = QtWidgets.QAction(MainWindow)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/images/format-indent-less.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFormatDecreaseIndent.setIcon(icon18)
        self.actionFormatDecreaseIndent.setObjectName("actionFormatDecreaseIndent")
        self.actionFormatBulletedList = QtWidgets.QAction(MainWindow)
        self.actionFormatBulletedList.setCheckable(True)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/images/bulleted-list.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFormatBulletedList.setIcon(icon19)
        self.actionFormatBulletedList.setObjectName("actionFormatBulletedList")
        self.actionFormatNumberedList = QtWidgets.QAction(MainWindow)
        self.actionFormatNumberedList.setCheckable(True)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(":/images/numbered-list.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFormatNumberedList.setIcon(icon20)
        self.actionFormatNumberedList.setObjectName("actionFormatNumberedList")
        self.actionInsertImage = QtWidgets.QAction(MainWindow)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(":/images/image-x-generic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionInsertImage.setIcon(icon21)
        self.actionInsertImage.setObjectName("actionInsertImage")
        self.actionCreateLink = QtWidgets.QAction(MainWindow)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(":/images/text-html.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCreateLink.setIcon(icon22)
        self.actionCreateLink.setObjectName("actionCreateLink")
        self.actionZoomOut = QtWidgets.QAction(MainWindow)
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(":/images/list-remove.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoomOut.setIcon(icon23)
        self.actionZoomOut.setObjectName("actionZoomOut")
        self.actionZoomIn = QtWidgets.QAction(MainWindow)
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap(":/images/list-add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoomIn.setIcon(icon24)
        self.actionZoomIn.setObjectName("actionZoomIn")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionStyleParagraph = QtWidgets.QAction(MainWindow)
        self.actionStyleParagraph.setObjectName("actionStyleParagraph")
        self.actionStyleHeading1 = QtWidgets.QAction(MainWindow)
        self.actionStyleHeading1.setObjectName("actionStyleHeading1")
        self.actionStyleHeading2 = QtWidgets.QAction(MainWindow)
        self.actionStyleHeading2.setObjectName("actionStyleHeading2")
        self.actionStyleHeading3 = QtWidgets.QAction(MainWindow)
        self.actionStyleHeading3.setObjectName("actionStyleHeading3")
        self.actionStyleHeading4 = QtWidgets.QAction(MainWindow)
        self.actionStyleHeading4.setObjectName("actionStyleHeading4")
        self.actionStyleHeading5 = QtWidgets.QAction(MainWindow)
        self.actionStyleHeading5.setObjectName("actionStyleHeading5")
        self.actionStyleHeading6 = QtWidgets.QAction(MainWindow)
        self.actionStyleHeading6.setObjectName("actionStyleHeading6")
        self.actionStylePreformatted = QtWidgets.QAction(MainWindow)
        self.actionStylePreformatted.setObjectName("actionStylePreformatted")
        self.actionStyleAddress = QtWidgets.QAction(MainWindow)
        self.actionStyleAddress.setObjectName("actionStyleAddress")
        self.actionFormatFontName = QtWidgets.QAction(MainWindow)
        self.actionFormatFontName.setObjectName("actionFormatFontName")
        self.actionFormatTextColor = QtWidgets.QAction(MainWindow)
        self.actionFormatTextColor.setObjectName("actionFormatTextColor")
        self.actionFormatBackgroundColor = QtWidgets.QAction(MainWindow)
        self.actionFormatBackgroundColor.setObjectName("actionFormatBackgroundColor")
        self.actionFormatFontSize = QtWidgets.QAction(MainWindow)
        self.actionFormatFontSize.setObjectName("actionFormatFontSize")
        self.actionInsertHtml = QtWidgets.QAction(MainWindow)
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap(":/images/insert-html.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionInsertHtml.setIcon(icon25)
        self.actionInsertHtml.setObjectName("actionInsertHtml")
        self.menu_File.addAction(self.actionFileNew)
        self.menu_File.addAction(self.actionFileOpen)
        self.menu_File.addAction(self.actionFileSave)
        self.menu_File.addAction(self.actionFileSaveAs)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionExit)
        self.menu_Edit.addAction(self.actionEditUndo)
        self.menu_Edit.addAction(self.actionEditRedo)
        self.menu_Edit.addSeparator()
        self.menu_Edit.addAction(self.actionEditCut)
        self.menu_Edit.addAction(self.actionEditCopy)
        self.menu_Edit.addAction(self.actionEditPaste)
        self.menu_Edit.addSeparator()
        self.menu_Edit.addAction(self.actionEditSelectAll)
        self.menu_Edit.addSeparator()
        self.menu_Edit.addAction(self.actionInsertImage)
        self.menu_Edit.addAction(self.actionCreateLink)
        self.menu_Edit.addAction(self.actionInsertHtml)
        self.menuSt_yle.addAction(self.actionStyleParagraph)
        self.menuSt_yle.addAction(self.actionStyleHeading1)
        self.menuSt_yle.addAction(self.actionStyleHeading2)
        self.menuSt_yle.addAction(self.actionStyleHeading3)
        self.menuSt_yle.addAction(self.actionStyleHeading4)
        self.menuSt_yle.addAction(self.actionStyleHeading5)
        self.menuSt_yle.addAction(self.actionStyleHeading6)
        self.menuSt_yle.addAction(self.actionStylePreformatted)
        self.menuSt_yle.addAction(self.actionStyleAddress)
        self.menu_Align.addAction(self.actionFormatAlignLeft)
        self.menu_Align.addAction(self.actionFormatAlignCenter)
        self.menu_Align.addAction(self.actionFormatAlignRight)
        self.menu_Align.addAction(self.actionFormatAlignJustify)
        self.menuF_ormat.addAction(self.menuSt_yle.menuAction())
        self.menuF_ormat.addAction(self.menu_Align.menuAction())
        self.menuF_ormat.addSeparator()
        self.menuF_ormat.addAction(self.actionFormatBold)
        self.menuF_ormat.addAction(self.actionFormatItalic)
        self.menuF_ormat.addAction(self.actionFormatUnderline)
        self.menuF_ormat.addAction(self.actionFormatStrikethrough)
        self.menuF_ormat.addSeparator()
        self.menuF_ormat.addAction(self.actionFormatIncreaseIndent)
        self.menuF_ormat.addAction(self.actionFormatDecreaseIndent)
        self.menuF_ormat.addSeparator()
        self.menuF_ormat.addAction(self.actionFormatNumberedList)
        self.menuF_ormat.addAction(self.actionFormatBulletedList)
        self.menuF_ormat.addSeparator()
        self.menuF_ormat.addAction(self.actionFormatFontName)
        self.menuF_ormat.addAction(self.actionFormatFontSize)
        self.menuF_ormat.addSeparator()
        self.menuF_ormat.addAction(self.actionFormatTextColor)
        self.menuF_ormat.addAction(self.actionFormatBackgroundColor)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Edit.menuAction())
        self.menubar.addAction(self.menuF_ormat.menuAction())
        self.standardToolBar.addAction(self.actionFileNew)
        self.standardToolBar.addAction(self.actionFileOpen)
        self.standardToolBar.addAction(self.actionFileSave)
        self.standardToolBar.addSeparator()
        self.standardToolBar.addAction(self.actionEditUndo)
        self.standardToolBar.addAction(self.actionEditRedo)
        self.standardToolBar.addSeparator()
        self.standardToolBar.addAction(self.actionEditCut)
        self.standardToolBar.addAction(self.actionEditCopy)
        self.standardToolBar.addAction(self.actionEditPaste)
        self.standardToolBar.addSeparator()
        self.standardToolBar.addAction(self.actionZoomOut)
        self.standardToolBar.addAction(self.actionZoomIn)
        self.formatToolBar.addAction(self.actionFormatBold)
        self.formatToolBar.addAction(self.actionFormatItalic)
        self.formatToolBar.addAction(self.actionFormatUnderline)
        self.formatToolBar.addAction(self.actionFormatStrikethrough)
        self.formatToolBar.addSeparator()
        self.formatToolBar.addAction(self.actionFormatAlignLeft)
        self.formatToolBar.addAction(self.actionFormatAlignCenter)
        self.formatToolBar.addAction(self.actionFormatAlignRight)
        self.formatToolBar.addAction(self.actionFormatAlignJustify)
        self.formatToolBar.addSeparator()
        self.formatToolBar.addAction(self.actionFormatDecreaseIndent)
        self.formatToolBar.addAction(self.actionFormatIncreaseIndent)
        self.formatToolBar.addSeparator()
        self.formatToolBar.addAction(self.actionFormatNumberedList)
        self.formatToolBar.addAction(self.actionFormatBulletedList)
        self.formatToolBar.addSeparator()
        self.formatToolBar.addAction(self.actionInsertImage)
        self.formatToolBar.addAction(self.actionCreateLink)
        self.formatToolBar.addAction(self.actionInsertHtml)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "HTML Editor"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.menu_File.setTitle(_translate("MainWindow", "&File"))
        self.menu_Edit.setTitle(_translate("MainWindow", "&Edit"))
        self.menuF_ormat.setTitle(_translate("MainWindow", "F&ormat"))
        self.menuSt_yle.setTitle(_translate("MainWindow", "St&yle"))
        self.menu_Align.setTitle(_translate("MainWindow", "&Align"))
        self.standardToolBar.setWindowTitle(_translate("MainWindow", "Standard"))
        self.formatToolBar.setWindowTitle(_translate("MainWindow", "Formatting"))
        self.actionFileNew.setText(_translate("MainWindow", "&New"))
        self.actionFileNew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionFileOpen.setText(_translate("MainWindow", "&Open..."))
        self.actionFileOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionFileSave.setText(_translate("MainWindow", "&Save"))
        self.actionFileSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionFileSaveAs.setText(_translate("MainWindow", "Save &As..."))
        self.actionEditUndo.setText(_translate("MainWindow", "&Undo"))
        self.actionEditUndo.setShortcut(_translate("MainWindow", "Ctrl+Z"))
        self.actionEditRedo.setText(_translate("MainWindow", "&Redo"))
        self.actionEditRedo.setShortcut(_translate("MainWindow", "Ctrl+Y"))
        self.actionEditCut.setText(_translate("MainWindow", "Cu&t"))
        self.actionEditCut.setShortcut(_translate("MainWindow", "Ctrl+X"))
        self.actionEditCopy.setText(_translate("MainWindow", "&Copy"))
        self.actionEditCopy.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.actionEditPaste.setText(_translate("MainWindow", "&Paste"))
        self.actionEditPaste.setShortcut(_translate("MainWindow", "Ctrl+V"))
        self.actionEditSelectAll.setText(_translate("MainWindow", "Select A&ll"))
        self.actionEditSelectAll.setShortcut(_translate("MainWindow", "Ctrl+A"))
        self.actionFormatBold.setText(_translate("MainWindow", "&Bold"))
        self.actionFormatBold.setShortcut(_translate("MainWindow", "Ctrl+B"))
        self.actionFormatItalic.setText(_translate("MainWindow", "&Italic"))
        self.actionFormatItalic.setShortcut(_translate("MainWindow", "Ctrl+I"))
        self.actionFormatUnderline.setText(_translate("MainWindow", "&Underline"))
        self.actionFormatUnderline.setShortcut(_translate("MainWindow", "Ctrl+U"))
        self.actionFormatStrikethrough.setText(_translate("MainWindow", "&Strikethrough"))
        self.actionFormatAlignLeft.setText(_translate("MainWindow", "Align &Left"))
        self.actionFormatAlignCenter.setText(_translate("MainWindow", "Align &Center"))
        self.actionFormatAlignRight.setText(_translate("MainWindow", "Align &Right"))
        self.actionFormatAlignJustify.setText(_translate("MainWindow", "Align &Justify"))
        self.actionFormatIncreaseIndent.setText(_translate("MainWindow", "I&ncrease Indent"))
        self.actionFormatDecreaseIndent.setText(_translate("MainWindow", "&Decrease Indent"))
        self.actionFormatBulletedList.setText(_translate("MainWindow", "Bulle&ted List"))
        self.actionFormatNumberedList.setText(_translate("MainWindow", "&Numbered List"))
        self.actionInsertImage.setText(_translate("MainWindow", "Insert &Image..."))
        self.actionCreateLink.setText(_translate("MainWindow", "Create Link..."))
        self.actionZoomOut.setText(_translate("MainWindow", "Zoom Out"))
        self.actionZoomIn.setText(_translate("MainWindow", "Zoom In"))
        self.actionExit.setText(_translate("MainWindow", "E&xit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionStyleParagraph.setText(_translate("MainWindow", "&Paragraph"))
        self.actionStyleHeading1.setText(_translate("MainWindow", "Heading &1"))
        self.actionStyleHeading2.setText(_translate("MainWindow", "Heading &2"))
        self.actionStyleHeading3.setText(_translate("MainWindow", "Heading &3"))
        self.actionStyleHeading4.setText(_translate("MainWindow", "Heading &4"))
        self.actionStyleHeading5.setText(_translate("MainWindow", "Heading &5"))
        self.actionStyleHeading6.setText(_translate("MainWindow", "Heading &6"))
        self.actionStylePreformatted.setText(_translate("MainWindow", "Pre&formatted"))
        self.actionStyleAddress.setText(_translate("MainWindow", "&Address"))
        self.actionFormatFontName.setText(_translate("MainWindow", "&Font Name..."))
        self.actionFormatTextColor.setText(_translate("MainWindow", "Text &Color..."))
        self.actionFormatBackgroundColor.setText(_translate("MainWindow", "Bac&kground Color..."))
        self.actionFormatFontSize.setText(_translate("MainWindow", "Font Si&ze..."))
        self.actionInsertHtml.setText(_translate("MainWindow", "Insert HTML..."))
        self.actionInsertHtml.setToolTip(_translate("MainWindow", "Insert HTML"))


from PyQt5 import QtWebEngineWidgets
from pyhtmleditor.ui import htmleditor_rc
